### ISSUE TITLE
Move ipaddr documentation from netcommon to utils 

### ISSUE THREAD

**Issue by ashwini-mhatre** [ansible-collections/ansible.utils#130]
##### SUMMARY

As we are migrating ipaddr filters from netcommon to utils,
We need to update https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters_ipaddr.html documentation.

##### ISSUE TYPE
- Documentation Report

##### ANSIBLE VERSION

```paste below

```

**Comment by ashwini-mhatre** [comment]
@samccann As we are migrating ipaddr plugins from netcommon to utils. we need to update respective documentation. Could you please look into this. I will help you if you need anything from my side.

**Comment by ashwini-mhatre** [comment]
CC: @trishnaguha @Qalthos

**Comment by samccann** [comment]
Hi @ashwini-mhatre - since the ipaddr documentation page only applies to the ansible.utils collection, this might be a good time to move the docs into that collection. We've done this for a handful of collection scenario guides and it seems to work well.  The gist of it is, we move the rst file into the collection in the docs/docsite/rst folder and then remove that document from ansible/ansible repository once the collection is updated in the Ansible package.  Does this sound like a reasonable approach to you?  It means the ipaddr document would show up at the top of the ansible.utils page on docs.ansible.com, kind of like we have guides up now on community.general - https://docs.ansible.com/ansible/latest/collections/community/general/index.html#plugins-in-community-general
![image](https://user-images.githubusercontent.com/30267855/150418899-ed9bec95-3151-4f6a-bbd5-3212e7384b75.png)

I think this might make it more findable than where it is today. And we could put in a redirect from the old page to this new site once it's published.

**Comment by ashwini-mhatre** [comment]
@samccann sounds good to me.
